title: Chandresh
email: hi@chandresh.xyz
description: Personal Website of Chandresh
url: "https://chandresh.xyz"
twitter: thisischandresh

baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed
